name: Base commit 

on:
  push:
    branches-ignore:
      - main

concurrency:
  group: base-commit-${{ github.ref }}
  cancel-in-progress: true

jobs:
  apply:
    uses: ./.github/workflows/.terraform.yml
    name: (PRD) Apply 
    with:
      tf_command: "apply"
    secrets:
      aws_secret_key:     ${{ secrets.AWS_SECRET_KEY_MAIN }}
      aws_access_key:     ${{ secrets.AWS_ACCESS_KEY_MAIN }}
      aws_region:         ${{ secrets.AWS_REGION }}

      aws_backend_bucket: ${{ secrets.AWS_BACKEND_BUCKET }}
      aws_backend_region: ${{ secrets.AWS_BACKEND_REGION }}
      aws_backend_key:    ${{ secrets.AWS_BACKEND_INFRA_KEY }}

      acm_crt:     ${{ secrets.API_DEVICE_KEY_PRD }}
      bucket_name: ${{ secrets.SITE_BUCKET_NAME }}