name: Build and Deploy to S3

on:
  push:
    branches-ignore:
      - main

concurrency:
  group: base-commit-${{ github.ref }}
  cancel-in-progress: true

jobs:
  terraform-apply:
    uses: ./.github/workflows/.terraform.yml
    name: (PRD) Apply Terraform
    with:
      tf_command: "apply"
    secrets:
      aws_secret_key:     ${{ secrets.AWS_SECRET_KEY_MAIN }}
      aws_access_key:     ${{ secrets.AWS_ACCESS_KEY_MAIN }}
      aws_region:         ${{ secrets.AWS_REGION }}
      aws_backend_bucket: ${{ secrets.AWS_BACKEND_BUCKET }}
      aws_backend_region: ${{ secrets.AWS_BACKEND_REGION }}
      aws_backend_key:    ${{ secrets.AWS_BACKEND_KEY }}
      acm_crt:            ${{ secrets.ACM_CRT }}
      bucket_name:        ${{ secrets.SITE_BUCKET_NAME }}

  build:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build site
        uses: Mad-Pixels/github-workflows/.github/actions/taskfile-runner@main
        with:
          command: docs/build

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: site-build
          path: docs/.vitepress/dist/
          retention-days: 1

  upload:
    needs: [build, terraform-apply]
    runs-on: ubuntu-24.04
    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: site-build
          path: dist_files

      - name: Upload to S3
        uses: Mad-Pixels/github-workflows/.github/actions/aws-s3-sync@main
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_MAIN }}
          aws_secret_key: ${{ secrets.AWS_SECRET_KEY_MAIN }}
          aws_region: ${{ secrets.AWS_REGION }}
          bucket_name: ${{ secrets.SITE_BUCKET_NAME }}
          source_dir: "dist_files"
          bucket_prefix: ""