name: Main PR Merged

on:
  pull_request:
    types: [closed]
    branches:
      - main

concurrency:
  group: main-pr-merged-${{ github.ref }}
  cancel-in-progress: true

jobs:
  apply:
    if: github.event.pull_request.merged == true
    uses: ./.github/workflows/.terraform.yml
    name: (PRD) Apply
    with:
      tf_command: "apply"
    secrets:
      aws_access_key:     ${{ secrets.AWS_ACCESS_KEY_MAIN }}
      aws_secret_key:     ${{ secrets.AWS_SECRET_KEY_MAIN }}
      aws_region:         ${{ secrets.AWS_REGION }}

      aws_backend_bucket: ${{ secrets.AWS_BACKEND_BUCKET }}
      aws_backend_region: ${{ secrets.AWS_BACKEND_REGION }}
      aws_backend_key:    ${{ secrets.AWS_BACKEND_KEY }}

      acm_crt:            ${{ secrets.ACM_CRT }}
      bucket_name:        ${{ secrets.SITE_BUCKET_NAME }}

  build:
    runs-on: ubuntu-24.04
    name: (PRD) Build
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build site
        uses: Mad-Pixels/github-workflows/.github/actions/taskfile-runner@main
        with:
          command: docs/build

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: site-build
          path: docs/.vitepress/dist/
          retention-days: 7

  publish:
    needs: [build, apply]
    runs-on: ubuntu-24.04
    name: (PRD) Publish
    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: site-build
          path: build-output

      - name: Upload to S3
        uses: Mad-Pixels/github-workflows/.github/actions/aws-s3-sync@main
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_MAIN }}
          aws_secret_key: ${{ secrets.AWS_SECRET_KEY_MAIN }}
          aws_region:     ${{ secrets.AWS_REGION }}

          bucket_name:    "go-dyno-docs-${{ secrets.SITE_BUCKET_NAME }}"
          source_dir:     "build-output"

      - name: Invalidate CloudFront cache
        uses: Mad-Pixels/github-workflows/.github/actions/aws-cloudfront-invalidation@main
        with:
          aws_access_key:  ${{ secrets.AWS_ACCESS_KEY_MAIN }}
          aws_secret_key:  ${{ secrets.AWS_SECRET_KEY_MAIN }}
          aws_region:      ${{ secrets.AWS_REGION }}
          distribution_id: ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }}
          paths:           "/*"