name: Base commit 

on:
  push:
    branches-ignore:
      - main

concurrency:
  group: base-commit-${{ github.ref }}
  cancel-in-progress: true

jobs:
  apply:
    uses: ./.github/workflows/.terraform.yml
    name: (PRD) Apply 
    with:
      tf_command: "apply"
    secrets:
      aws_secret_key:     ${{ secrets.AWS_SECRET_KEY_MAIN }}
      aws_access_key:     ${{ secrets.AWS_ACCESS_KEY_MAIN }}
      aws_region:         ${{ secrets.AWS_REGION }}

      aws_backend_bucket: ${{ secrets.AWS_BACKEND_BUCKET }}
      aws_backend_region: ${{ secrets.AWS_BACKEND_REGION }}
      aws_backend_key:    ${{ secrets.AWS_BACKEND_KEY }}

      acm_crt:     ${{ secrets.ACM_CRT }}
      bucket_name: ${{ secrets.SITE_BUCKET_NAME }}

  build:
    uses: Mad-Pixels/github-workflows/.github/workflows/node-build.yml@main
    with:
      working-directory: ./
      node-version: '20'
  
  discover:
    needs: [build]
    runs-on: ubuntu-24.04
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: artifacts
          path: dist_files

  upload:
    needs: [build]
    uses: Mad-Pixels/github-workflows/.github/workflows/aws-s3-sync.yml@main
    with:
      artifacts: "artifacts"
      working_directory: "dist_files"
      actions_verions: "0.0.1"
    secrets:
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_KEY }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
      BUCKET_DESTINATION: ${{ secrets.SITE_BUCKET_NAME }}
