name: Update Docs

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Tag version'
        required: true
        type: string

jobs:
  update-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout docs repo
        uses: actions/checkout@v4

      - name: Prepare new version
        run: |
          VERSION="${{ github.event.inputs.version }}"
          DOCS_DIR="docs"

          for LOCALE_DIR in $DOCS_DIR/*; do
            if [[ -d "$LOCALE_DIR" ]]; then
              LOCALE=$(basename "$LOCALE_DIR")

              if [[ "$LOCALE" =~ ^[a-z]{2}$ ]]; then
                VERSIONS=($(ls -d "$LOCALE_DIR"/v* 2>/dev/null | xargs -n1 basename | sort -V))
                LAST_VERSION="${VERSIONS[-1]}"

                SRC="$LOCALE_DIR/$LAST_VERSION"
                DST="$LOCALE_DIR/$VERSION"

                if [[ -d "$DST" ]]; then
                  echo "Destination $DST already exists, skipping."
                else 
                  cp -r "$SRC" "$DST"
                fi
              fi
            fi
          done
      
      - name: Create Pull RequestAdd commentMore actions
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.PAT_TOKEN }}
          commit-message: "🤖 docs: add version ${{ github.event.inputs.version }}"
          branch: "docs/${{ github.event.inputs.version }}"
          title: "🚀 GoDyno new docs Release: ${{ github.event.inputs.version }}"
          body: |
            🚀 A new **GoDyno** release has been detected: `${{ github.event.inputs.version }}`

            This PR contains a new versioned copy of the documentation.

            ---
            ✅ Auto-generated by CI.

            📌 **Before merging**, please update the documentation according to the latest changes in the CLI application.

            _See the [changelog](https://github.com/Mad-Pixels/go-dyno/blob/main/CHANGELOG.md) on the `main` branch for details._
